In [1]:
import pandas as pd

In [ ]:
# series and dataframe is data structure
# series -> 1d
series = pd.Series([100,200,300,400],index=['a','b','c','d'])
series

a    100
b    200
c    300
d    400
dtype: int64

In [ ]:
# dataframe -> 2d
df = pd.DataFrame({"name":["akshit","ankur","anish"] , "marks":[100,98,90]})
df

     name  marks
0  akshit    100
1   ankur     98
2   anish     90

In [18]:
file = pd.read_csv("data/1.csv")
file.head()

,id,first_name,last_name,email,age,city,salary,joined
0,1,Liam,Williams,liam.williams1@sample.net,49,Riverside,156973.24,2020-04-18
1,2,Jane,Williams,jane.williams2@example.com,71,Fairview,50435.05,2024-01-27
2,3,Emma,Moore,emma.moore3@test.org,76,Fairview,128705.61,2022-01-06
3,4,Emma,Martinez,emma.martinez4@example.com,43,Burlington,106198.11,2016-01-05
4,5,Benjamin,Rodriguez,benjamin.rodriguez5@sample.net,62,Manchester,189641.05,2023-04-19

In [19]:
file.describe()

             id        age         salary
count  10.00000  10.000000      10.000000
mean    5.50000  46.900000  103713.770000
std     3.02765  18.764328   65217.194142
min     1.00000  21.000000   22669.840000
25%     3.25000  31.000000   37387.660000
50%     5.50000  46.000000  117451.860000
75%     7.75000  60.000000  154446.692500
max    10.00000  76.000000  189641.050000

In [20]:
file.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          10 non-null     int64
 1   first_name  10 non-null     str
 2   last_name   10 non-null     str
 3   email       10 non-null     str
 4   age         10 non-null     int64
 5   city        10 non-null     str
 6   salary      10 non-null     float64
 7   joined      10 non-null     str
dtypes: float64(1), int64(2), str(5)
memory usage: 772.0 bytes

In [21]:
file["id"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: id, dtype: int64

In [22]:
file[["id","email"]]

   id                           email
0   1       liam.williams1@sample.net
1   2      jane.williams2@example.com
2   3            emma.moore3@test.org
3   4      emma.martinez4@example.com
4   5  benjamin.rodriguez5@sample.net
5   6        amelia.williams6@demo.io
6   7              mia.jones7@demo.io
7   8             emma.lopez8@demo.io
8   9      isabella.lopez9@sample.net
9  10        amelia.johnson10@demo.io

In [23]:
file

,id,first_name,last_name,email,age,city,salary,joined
0,1,Liam,Williams,liam.williams1@sample.net,49,Riverside,156973.24,2020-04-18
1,2,Jane,Williams,jane.williams2@example.com,71,Fairview,50435.05,2024-01-27
2,3,Emma,Moore,emma.moore3@test.org,76,Fairview,128705.61,2022-01-06
3,4,Emma,Martinez,emma.martinez4@example.com,43,Burlington,106198.11,2016-01-05
4,5,Benjamin,Rodriguez,benjamin.rodriguez5@sample.net,62,Manchester,189641.05,2023-04-19
5,6,Amelia,Williams,amelia.williams6@demo.io,34,Manchester,26628.09,2016-08-19
6,7,Mia,Jones,mia.jones7@demo.io,21,Ashland,33038.53,2021-01-03
7,8,Emma,Lopez,emma.lopez8@demo.io,30,Greenville,146867.05,2015-12-15
8,9,Isabella,Lopez,isabella.lopez9@sample.net,29,Greenville,175981.13,2015-01-27
9,10,Amelia,Johnson,amelia.johnson10@demo.io,54,Madison,22669.84,2020-03-09

In [26]:
# help to see entire row
file.iloc[0]

id                                    1
first_name                         Liam
last_name                      Williams
email         liam.williams1@sample.net
age                                  49
city                          Riverside
salary                        156973.24
joined                       2020-04-18
Name: 0, dtype: object